name: Check pull request
on: [pull_request]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Check frontend
        run: cd src/frontend && npm ci && npm run check
      - name: Check backend
        run: cd src/backend/api && npm ci && npm run check
